repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: sort-simple-yaml

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
